- .gitignore
Suggesting a gitignore pattern that would be less likely to lead to surprising behavior (for other contributors).
> Adjust gitignore

- sql/new_queries/README.md
Adding a new_queries subdirectory under 'sql' for people working exclusively on github.com
> adding new_queries subdirectory

- reports/README.md
- sql/title_count/README.md
- sql/title_count/title_count_v0.83.sql
As dicussed with @amzoss this is a beta version of the query.
> Added title count query and first version of documentation 

- sql/acrl/circulation/acrl_circulation.sql
- sql/acrl/circulation/acrl_location_filtering.sql
- sql/acrl/circulation/acrl_parameters.sql
- sql/circ_item_detail/circ_item_detail.sql
Suggested edits after testing with live data
> Proposed query changes (circ_item_detail) and factoring (acrl_circulation)

- sql/derived_tables/users_addresses.sql
- sql/derived_tables/users_departments_unpacked.sql
- sql/derived_tables/users_groups.sql
incomplete (waiting on additional tables) but should be working as is
> adding early versions of new user expansion tables

- sql/derived_tables/instance_alternative_titles.sql
- sql/derived_tables/instance_contributors.sql
Here are the 2 new derived tables that I did.
1. https://github.com/folio-org/folio-analytics/issues/100. This is the instance_contributors.sql
2. https://github.com/folio-org/folio-analytics/issues/99. This is the instance_alternative_titles.sql
I removed the vacuum and analyze from both of these. I also tried to respect the formatting.
Best,
Jennifer
> 2 new derived tables

- sql/derived_tables/instances_publication.sql
> Fix minor formatting in instances_publication

- README.md
> Fix broken links to report queries

- sql/derived_tables/po_lines_eresource.sql
- sql/derived_tables/po_lines_physical.sql
> FIx formatting in po_lines_* queries

- sql/derived_tables/feesfines_accounts_actions.sql
> Use json_extract_path_text() to work around missing data

- sql/derived_tables/item_ext.sql
> Update MM Item_ext Derived table

- sql/derived_tables/feesfines_accounts_actions.sql
- sql/derived_tables/holdings_ext.sql
- sql/derived_tables/instance_contributors.sql
- sql/derived_tables/invoice_lines_adjustments.sql
- sql/derived_tables/invoice_lines_fund_distributions.sql
- sql/derived_tables/item_ext.sql
- sql/derived_tables/po_instance.sql
- sql/derived_tables/po_lines_eresource.sql
> Cast non-string JSON data types to SQL equivalent

- sql/report_queries/README.md
should close #235 and generally make README more up-to-date
> add note about derived tables, update TOC

- sql/report_queries/orders/orders.sql
Changed:
OR pol.pol_subscription_from <= (
SELECT
subscription_to_date
to:
OR pol.pol_subscription_from < (
SELECT
subscription_to_date
> update to half-open interval for date range

- sql/derived_tables/instance_ext.sql
… instance property "previouslyHeld".
> Test PR 343

- sql/report_queries/shelf_list/shelf_list.sql
> updated loc filtering in shelf list

- sql/report_queries/shelf_list/README.md
> add readme for shelf list report

- sql/report_queries/erm/count/README.md
- sql/report_queries/erm/count/erm_inventory_count.sql
- sql/report_queries/item_count/README.md
- sql/report_queries/item_count/item_count.sql
- sql/report_queries/title_count/README.md
- sql/report_queries/title_count/title_count.sql
Added Holdings and Items discovery_suppress to the Title Count and Item Count queries and updated query documentation
> Fixes #344

- sql/derived_tables/instance_relationships_ext.sql
> Fix for derived tables issue in instance_relationships_ext table script.

- sql/derived_tables/users_departments_unpacked.sql
can be tested on folio_snapshot_20210329
will close #308
> updating users_departments_unpacked.sql with now-available department fields 

- sql/derived_tables/deps.txt
- sql/derived_tables/locations_service_points.sql
- sql/derived_tables/runlist.txt
> Test PR 407

- sql/derived_tables/deps.txt
- sql/derived_tables/locations_service_points.sql
- sql/derived_tables/runlist.txt
> adding a new derived table to unpack service points

- sql/derived_tables/loans_renewal_dates.sql
- sql_2g/derived_tables/loans_renewal_dates.sql
will close #406
(note: no change to query functionality. Just removing comment lines.)
> remove old developer comments

- sql/report_queries/requests/requests.sql
> Adding requests query

- sql/report_queries/item_related_exceptions/README.md
- sql/report_queries/item_related_exceptions/item_related_exceptions.sql
This can be tested against `folio_snapshot_20210414_circlog`
Thanks to @lib-eric for the suggestions! (#436)
> slight fixes to fix duplication, improve documentation link

- sql_metadb/derived_tables/agreements_custom_property.sql
A few additional attributes for the derived table agreements_custom_property. In particular, the ID for linking to the subscription_agreement table.
> Additional attributes for the derived table agreements_custom_property

- sql/report_queries/overdue_items/README.md
- sql/report_queries/overdue_items/overdue_items.sql
Should work on any standard day of folio_snapshot. Fixes #453
> Adding overdue_items report query

- sql_metadb/report_queries/erm/resource_lists/erm_agreement_package_content_item_list.sql
suggested changes for clarity or consistency
> proposed: minor changes to erm report

- sql/report_queries/missing_items/README.md
- sql/report_queries/missing_items/missing_items.sql
Runs on `folio_snapshot_20210525_missing` database. Fixes #422
> Adding missing_items report query

- sql/require_columns/ldp_add_column.conf
changes proposed by brichardEbsco
> add columns to circulation_loans

- sql/report_queries/HathiTrust reports/Monographic Holdings Report/README.md
- sql/report_queries/HathiTrust reports/Monographic Holdings Report/monographic_holdings.sql
- sql/report_queries/HathiTrust reports/Multipart Monographs Holdings Report/README.md
- sql/report_queries/HathiTrust reports/Multipart Monographs Holdings Report/multipart_monographs_holdings.sql
- sql/report_queries/HathiTrust reports/Serials Holdings Report/README.md
- sql/report_queries/HathiTrust reports/Serials Holdings Report/serials_holdings.sql
This closes issue #450, issue #451, issue #449.
I was only able to test these reports using FOLIO Snapshot. Cornell has tested the monographs and multipart monographs. However, these should be tested with a larger set and better data.
> New HathiTrust reports

- CONTRIBUTING.md
This clarifies in the contribution guidelines that commits and pull requests should be documented.  Pull request descriptions should be self-contained and descriptive enough to be included in the merge commit.
> Request documentation of commits and pull requests

- sql_metadb/derived_tables/holding_notes.sql
- sql_metadb/derived_tables/runlist.txt
New derived table for holdings, also added to runlist.txt file , holdings_notes
> new derived table hold notes

- sql_metadb/derived_tables/holdings_statistical_codes.sql
- sql_metadb/derived_tables/runlist.txt
new derived table, added to run list as well
> new derived table Hold stat codes

- sql_metadb/derived_tables/po_lines_details_subscription.sql
- sql_metadb/derived_tables/runlist.txt
> Adding port po_lines_details_subscription derived table to Metadb 

- sql_metadb/derived_tables/invoice_voucher_lines_fund_distributions.sql
- sql_metadb/derived_tables/runlist.txt
> Adding port of invoice_voucher_lines_fund_distributions derived table to Metadb

- sql_metadb/derived_tables/po_lines_er_mat_type.sql
- sql_metadb/derived_tables/runlist.txt
> Adding port po_lines_er_mat_type derived table to Metadb 

- sql_metadb/derived_tables/po_lines_eresource.sql
- sql_metadb/derived_tables/runlist.txt
> Adding port po_lines_eresource derived table to Metadb

- sql_metadb/derived_tables/po_lines_phys_mat_type.sql
- sql_metadb/derived_tables/runlist.txt
>  Adding port po_lines_phys_mat_type derived table to Metadb

- sql_metadb/derived_tables/holdings_statements_supplements.sql
- sql_metadb/derived_tables/runlist.txt
create new metadb table holdings_statement_supplement
> new metadb table Holdings statements supplements

- sql_metadb/derived_tables/holdings_statements.sql
- sql_metadb/derived_tables/runlist.txt
add new metadb derived table for holdings also added to runlist
> new metadb derived table Holdings statements

- sql/derived_tables/holdings_statements_indexes.sql
- sql_metadb/derived_tables/holdings_statements_index.sql
- sql_metadb/derived_tables/runlist.txt
added new metadb holdings_statements_indexes table, also added to runlist
> Holdings statements index

- sql_metadb/derived_tables/instance_ext.sql
- sql_metadb/derived_tables/runlist.txt
New metadb derived table for instance.ext
> MM - Porting over Derived Table Instance ext

- sql_metadb/derived_tables/instance_editions.sql
- sql_metadb/derived_tables/runlist.txt
New derived tabled ported over for instance editions
> MM Ported Over Derived Table Instance editions for Metadb

- sql_metadb/derived_tables/instance_languages.sql
- sql_metadb/derived_tables/runlist.txt
New derived table for instances languages
> MM Port Over LDP Instance languages to Metadb

- sql_metadb/derived_tables/instance_nature_content.sql
- sql_metadb/derived_tables/runlist.txt
> MM Ported Over Instance Nature of content

- sql_metadb/derived_tables/holdings_electronic_access.sql
- sql_metadb/derived_tables/runlist.txt
added new derived table holdings_electronic_access
> Hold notes eaccess

- sql_metadb/derived_tables/po_lines_physical.sql
- sql_metadb/derived_tables/runlist.txt
> Adding port po_lines_physical derived table to Metadb

- sql_metadb/derived_tables/po_ongoing.sql
- sql_metadb/derived_tables/runlist.txt
>  Adding port po_ongoing derived table to Metadb

- sql_metadb/derived_tables/agreements_subscription_agreement_entitlement.sql
> Fixed data type in agreements_subscription_agreement_entitlement.sql

- sql_metadb/derived_tables/instance_ext.sql
For system created FOLIO fields of cataloged and updated date change casting to timestamptz.
> MM, Metadb derived table Instance_ext changed Date to timestamptz

- sql_metadb/derived_tables/runlist.txt
- sql_metadb/derived_tables/users_groups.sql
Ported derived table users_groups from LDP to MetaDB. closes #603 #490
> RA/UM - Port derived table users_groups for metadb

- sql_metadb/derived_tables/instance_publication.sql
- sql_metadb/derived_tables/runlist.txt
This is a new ported over derived table for publication information in FOLIO instances.
> MM New Ported Derived Table for MetadDB Instance publication

- sql_metadb/derived_tables/instance_notes.sql
- sql_metadb/derived_tables/runlist.txt
New ported derived table for metaDB for instance_notes
> MM MetaDB Derived Table Instance notes

- sql_metadb/derived_tables/instance_series.sql
- sql_metadb/derived_tables/runlist.txt
New derived table ported from LDP to MetaDB for series information in instance records
> MM Ported Over Derived Table Instance series

- sql_metadb/derived_tables/instance_subjects.sql
- sql_metadb/derived_tables/runlist.txt
New ported over derived table for metadb to extract subjects from FOLIO instance records.
> MM Ported Over LDP to MetaDB Instance subjects

- sql_metadb/derived_tables/instance_classifications.sql
- sql_metadb/derived_tables/runlist.txt
This new derived table extracts classification ids, values, and names from the instance.
> MM New Derived Metadb table for Instance classifications

- sql_metadb/derived_tables/instance_identifiers.sql
- sql_metadb/derived_tables/runlist.txt
create new derived metadb table instance_identifiers
> Instance_identifiers

- sql_metadb/derived_tables/holdings_tags
- sql_metadb/derived_tables/holdings_tags.sql
- sql_metadb/derived_tables/runlist.txt
create new metadb derived table holdings_tags
> MM New derived table Holdings tags

- sql_metadb/derived_tables/licenses_license_ext.sql
Closes #636 
- The query has been adapted to the new data schema.
- Optimizations: Removed unnecessary aliases + changed aliases to clearlier names
> Fix licenses_license_ext

- sql_metadb/derived_tables/agreements_package_content_item.sql
Closes #633 
- The query has been adapted to the new data schema.
> Fix agreements_package_content_item

- sql/derived_tables/po_lines_locations.sql
This will add holding_id and relying locations resolving on newly introduced holding information at po line level for derived table po_lines_locations
This PR credits on the original PR #654 from @sbeltaine
> RM - update derived table po_lines_locations  / LDP

- sql/derived_tables/po_lines_eresource.sql
This will add holding_id and relying locations resolving on newly introduced holding information at po line level for derived table po_lines_eresource
> RM - update derived table po_lines_eresource / LDP

- CHANGES.md
- sql_metadb/derived_tables/agreements_custom_property.sql
Closes #629 
- Comments have been added to the columns, which can be retrieved within the table properties.
> ERM - Added comments to agreements_custom_property

- CHANGES.md
- sql_metadb/report_queries/erm/agreement_cancellation_dates/erm_agreement_cancellation_dates.sql
Closes #619 
The query has been adapted to the new data schema and got some improvements.
```
All queries:
```
> ERM - Bugfix erm_agreement_cancellation_dates.sql

- CHANGES.md
- sql/derived_tables/po_instance.sql
> changed cast for created_date for ldp Po_instance.sql

- CHANGES.md
- sql_metadb/derived_tables/agreements_subscription_agreement.sql
Will  fix #627 
Comments have been added to the columns, which can be retrieved within the table properties.
```
All queries:
```
> ERM - Added comments to agreements_subscription_agreement

- CHANGES.md
- sql_metadb/derived_tables/agreements_subscription_agreement_entitlement.sql
Will  fix #628 
Comments have been added to the columns, which can be retrieved within the table properties.
```
All queries:
```
> Add comments to agreements_subscription_agreement_entitlement

- CHANGES.md
- sql/derived_tables/po_lines_eresource.sql
- sql_metadb/derived_tables/po_lines_eresource.sql
- Added holding_id and relying locations resolving on newly introduced holding information at po line level for derived table po_lines_eresource (Metadb version)
- Added comments to derived table(s) po_lines_eresource
```
All queries:
```
> Updated derived tables po_lines_eresource

- CHANGES.md
- sql_metadb/derived_tables/po_lines_er_mat_type.sql
Added Comments to columns per API documentation 
```
All queries:
```
> Rm   po lines er mat type.sql

- CHANGES.md
- sql_metadb/derived_tables/agreements_subscription_agreement_org_ext.sql
- sql_metadb/derived_tables/finance_transaction_invoices.sql
- sql_metadb/derived_tables/invoice_adjustments_ext.sql
- sql_metadb/derived_tables/invoice_adjustments_in_addition_to.sql
- sql_metadb/derived_tables/po_lines_cost.sql
Related to #632. Adding field definitions as comments
```
All queries:
```
> Add comments for agreements_subscription_agreement_org_ext.sql

- CHANGES.md
- sql_metadb/derived_tables/agreements_package_content_item.sql
Closes #631 
Comments have been added to the columns, which can be retrieved within the table properties. The descriptions were taken from the documentation in Confluence.
```
All queries:
```
> ERM - Added comments and refactoring for Agreements_package_content_item

- CHANGES.md
- sql/derived_tables/locations_service_points.sql
- sql_metadb/derived_tables/locations_service_points.sql
- sql_metadb/derived_tables/runlist.txt
Adding new metadb derived table query, updating metadb runlist, improving style and documentation on LDP1 version, and editing CHANGES.md
```
All queries:
```
> adding metadb version of locations_service_points derived table

- sql/derived_tables/po_lines_vendor_reference_numbers.sql
> Fix apparent typo in COMMENT statements for derived table po_lines_vendor_reference_numbers

- reports/count_loans_and_renewals/README.md
- reports/count_loans_and_renewals/count_loans_and_renewals.json
- reports/count_loans_and_renewals/count_loans_and_renewals.sql
This is the old loans_and_renewals_counts report converted to the new Metadb-supported report format, which the LDP Reporting App is also planned to support.  This is a Metadb report.
> Convert loan count report to new report format

- sql/derived_tables/po_lines_fund_distribution.sql
* Use new form of JSON extraction for LDP
* Change column names to match source data
* Remove indexes for non-ID columns
* Remove VACUUM ANALYZE
* Use lateral join for array extraction
> Adjustments to po_lines_fund_distribution

- sql/derived_tables/item_administrative_notes.sql
- sql/derived_tables/runlist.txt
Backport item_administrative_notes to LDP
> Backport item_administrative_notes to LDP

- sql_metadb/derived_tables/finance_budgets.sql
- sql_metadb/derived_tables/runlist.txt
Addresses issue [#827](https://github.com/folio-org/folio-analytics/issues/827)
> Create new finance budget derived table

- sql_metadb/derived_tables/holdings_notes.sql
correction to updatedDate as note_date_updated,
updatedByUserId as as note_updated_by_user_id
and added instance_hrid field to a table
closes issue #871
> Update metadb holdings_notes.sql

- sql_metadb/derived_tables/po_instance.sql
added new fields and corrected pol locations
closes issue #851
> Update metadb po_instance derived table
