sql/derived_tables/README.md

Running a derived table query file in a transaction causes the drop
table statement to be rolled back if an error occurs while creating
the new table.  Allowing the drop table to be committed in such cases
is preferable to the possibility that users might query an old version
of the table without realizing it.  For this reason the example script
has been changed to run the SQL in autocommit mode.

Remove single-transaction flag in script

---

sql/derived_tables/loans_items.sql

Fixes an issue with derived table `loans_items` when a system has no renewals.

Use json_extract_path_text() to get renewal count from circulation_loans

---

sql/derived_tables/po_instance.sql

Resolves issue building table in systems that have no purchase orders.

Use json_extract_path_text() for po_number and vendor in po_instance derived table.

---

sql_2g/derived_tables/agreements_erm_resource.sql
sql_2g/derived_tables/agreements_subscription_agreement_entitlement.sql
sql_2g/report_queries/erm/README.md
sql_2g/report_queries/erm/costs/README.md
sql_2g/report_queries/erm/costs/erm_agreement_cost.sql
sql_2g/report_queries/erm/count/README.md
sql_2g/report_queries/erm/count/erm_agreement_count.sql

Adresses #282 and #283
Can only be tested against `reports_dev` 
Be aware that two derived tables have updates in this PR too and can be exchanged in `erm_agreement_count.sql` by `axeldoerrer_agreements_erm_resource`  and `axeldoerrer_agreements_subscription_agreement_entitlement ` in order to run it.

Created agreement cost and count queries for 2G

---

sql/report_queries/item_related_exceptions/README.md
sql/report_queries/item_related_exceptions/item_related_exceptions.sql

relevant data seems to come and go in folio_snapshot. We've had luck with the `folio_snapshot_20210414` database, but other dates might also work.

item-related exceptions report

---

sql/derived_tables/finance_transaction_invoices.sql
sql/derived_tables/finance_transaction_purchase_order.sql
sql_metadb/derived_tables/finance_transaction_invoices.sql
sql_metadb/derived_tables/finance_transaction_purchase_order.sql

Fixed issue that caused transactions to be duplicated because of lacking fiscal_year_id as additional key

Fix to address the duplication of transaction rows

---

sql/derived_tables/loans_items.sql
sql/report_queries/services_usage/services_usage.sql

JSON extract results in a string field in the derived table, so query was failing. fixing both the derived table and the report query, for good measure. Additional slight formatting changes for readability and consistency.

fixing timestamp conversion in services_usage and loans_items

---

sql/report_queries/patron_list/patron_list.sql

- improved notes list to include date of note
- improved comments to explain address type parameter
- removed direct column references that were preventing the query from running without notes and manual blocks data
best test data is in `folio_snapshot_20210602_users`, but query should also run without errors on snapshot now

updates to patron_list report query

---

sql_metadb/derived_tables/instance_formats.sql
sql_metadb/derived_tables/runlist.txt

New ported over instance formats derived table for Metadb.
**NOTE**: There is a problem with some of the FOLIO data for format ids. Instead of a uuid, there is text information. I had to treat the uuids here as varchar because of that.

MM - Port Over Derived Table Instance format ids for Metadb

---

sql_metadb/derived_tables/instance_ext.sql

This change removes a CTE that appears to be unnecessary in the instance_ext derived table.

Simplify instance_ext derived table

---

sql_metadb/derived_tables/agreements_subscription_agreement_org_ext.sql
sql_metadb/derived_tables/licenses_license_ext.sql

Column names now without quotes and data type for column "license_org_uuid" changed to UUID. The UUID for "license_id" must still be of the data type varchar (app-internal specification). "license_start" and "license_end" remain integer and must later be set to data type timestamptz. This is currently not possible. 
#551

Corrected data type and column names

---

sql_metadb/derived_tables/finance_po_inv_transactions.sql
sql_metadb/derived_tables/runlist.txt
sql_metadb/report_queries/administration/user_permission_sets.sql

#518 The table combines information about po (lines), invoice (lines), transactions and finance. The table is necessary to avoid cross-products in GUI-based reporting solutions. Attributes that affect the fiscal year rollover will be checked later and, if necessary, supplemented via a new issue.

Create derived table finance_po_inv_transactions

---

sql_metadb/derived_tables/item_notes.sql
sql_metadb/derived_tables/runlist.txt

Create a metadb derived table for notes on items. Table creates a new entry for every note and detailing type of note, note content, visibility of staff only or not, and the ordinality of the note appear in the item record.

Create metadb derived table item_notes

---

sql_metadb/derived_tables/item_statistical_codes.sql
sql_metadb/derived_tables/runlist.txt

Create a metadb derived table for statistical codes on items. Table captures the statistical code, the name of the code, and name of the code type.

Create MetaDB derived item_statistical_codes

---

sql_metadb/derived_tables/items_holdings_instances.sql
sql_metadb/derived_tables/runlist.txt

Create a metadb derived table for linking items to holdings to instance. Table is primarily item level with piece information such as volume and material type, but also has holding level details like call number fields, and at the instance level with title and cataloged date.

Create metadb derived table items_holdings_instances

---

sql_metadb/derived_tables/item_tags.sql
sql_metadb/derived_tables/runlist.txt

Create a metadb derived table for items with tags. Table contains a new row for every tag associated with an item record and contains the name of the tag and ordinality the tag appears in.

Create metadb derived table item_tags

---

sql_metadb/derived_tables/agreements_subscription_agreement_org_ext.sql

Due to data model changes on the role of organizations the derived table agreements_subscription_agreement_org_ext did not run anymore. Will fix #634

Bug fix for derived table agreements_subscription_agreement_org_ext 

---

CHANGES.md
sql/require_columns/ldp_add_column.conf

Add columns `finance_funds.fund_type_id` and `finance_transactions.description`. Allows the building of some finance tables when data is lacking.
Update has been tested against LDP 1.x datasets.

Add columns to ldp_add_columns.conf

---

CHANGES.md
sql_metadb/report_queries/erm/agreement_package_content_item_list/erm_agreement_package_content_item_list.sql

Closes #618 
Query ended with error: "Column reference 'res_name' is ambiguous". This error has been corrected.
```
All queries:
```

ERM - Bugfix erm_agreement_package_content_item_list.sql

---

CHANGES.md
sql/derived_tables/items_holdings_instances.sql

Fixes #693
Looked to the metadb version to decide which field to remove. Also noticed documentation was not at top of query, so moved that as well.
```
All queries:
```

Remove duplicate field from items_holdings_instances (bugfix for 1.5.0)

---

CHANGES.md
sql_metadb/derived_tables/invoice_lines_fund_distributions.sql
sql_metadb/derived_tables/po_lines_tags.sql

Fixes #596 
Add missing description comment to invoice_lines_fund_distributions and po_lines_tags derived tables for Metadb.
```
All queries:
```

Add missing descriptive comment in derived tables (bugfix for 1.5.0)

---

CHANGES.md
sql/derived_tables/finance_transaction_purchase_order.sql
sql_metadb/derived_tables/finance_transaction_purchase_order.sql

This bugfix adds the missing encumbrance status to derived table `finance_trancaction_purchase_order` which is essential for particular reporting needs. Fixes #640  
Because LDP1 version is also needed to be fixed missing comments have been copied as well.
```
All queries:
```

Add missing encumbrance status to derived table `finance_trancaction_purchase_order`  (bugfix for 1.5.0) 

---

sql_metadb/README.md

The porting.md file was removed in April with a commit message referencing the MetaDB documentation. This readme file was still pointing to the old porting.md file, so this updates the link to point to the MetaDB documentation.

Update link to migration info in sql_metadb/README.md

---

sql/require_columns/ldp_add_column.conf

This is for the derived tables for LDP1. Add missing datatypes for columns. Also add required column po_lines.selector (required by po_instance table build code). Resolves #749.

Fix po_lines columns in ldp_add_column.conf

---

sql_metadb/report_queries/erm/erm_inventory_cost/README.md
sql_metadb/report_queries/erm/erm_inventory_cost/erm_inventory_cost.sql

Closes #747 
Ported report from LDP1 to Metadb. The name of the subdirectory has been slightly changed to LDP1 version to avoid confusion with the report for agreements.
LDP1 version:
https://github.com/folio-org/folio-analytics/blob/main/sql/report_queries/erm/costs/erm_inventory_cost.sql

ACQ/ERM - Port Rpt ERM-Inventory Costs Cluster to Metadb

---

sql_metadb/report_queries/erm/eusage_counter_reports/eusage_counter_rpt_ir/README.md
sql_metadb/report_queries/erm/eusage_counter_reports/eusage_counter_rpt_ir/eusage_counter_rpt_ir.sql

Closes #768 
This report is intended to contain data from the FOLIO app eUsage. In this case, the report contains only data for Item Master Reports (IR). The required attributes can be found at https://medialibrary.projectcounter.org/file/The-Friendly-Guide-for-Librarians . In addition to this attributes there are attributes to the downloaded COUNTER report.
For performance reasons, the arrays are read based on positions.

ERM - Report 'eusage_counter_rpt_ir' for Metadb

---

sql_metadb/report_queries/erm/eusage_counter_reports/eusage_counter_rpt_tr/README.md
sql_metadb/report_queries/erm/eusage_counter_reports/eusage_counter_rpt_tr/eusage_counter_rpt_tr.sql

Closes #767 
This report is intended to contain data from the FOLIO app eUsage. In this case, the report contains only data for Title Master Reports (TR). The required attributes can be found at https://medialibrary.projectcounter.org/file/The-Friendly-Guide-for-Librarians . In addition to this attributes there are attributes to the downloaded COUNTER report.
For performance reasons, the arrays are read based on positions.

ERM - Report 'eusage_counter_rpt_tr' for Metadb

---

sql_metadb/derived_tables/holdings_ext.sql

Some production sites lack this data in their holdings records, which prevents the derived table `holdings_ext` from being built.

Require columns call_number_prefix and call_number_suffix in holdings_record__t

---

sql/derived_tables/holdings_electronic_access.sql
sql_metadb/derived_tables/holdings_electronic_access.sql

Add NULLIF function to address blank relationshipId values. Backport of #861

Check for empty string UUID in holdings_electronic_access

---

sql/derived_tables/loans_renewal_dates.sql

-- Changes to query: 
-- truncated the renewal date ("created date") to 'minutes' to eliminate renewals seconds apart, which are artifacts of system processes, not actual patron renewals.
-- added the item hrid
-- selected the loan status from the circulation_loans table, not the circulation_loan_history table (which always shows "Open" for renewals)
-- removed the loan history id ("id") from Select statement, since including it would make it impossible group by loan_id and count renewals
-- removed the "loan_renewal_count" field (selected from the circulation_loan_history table) to prevent misuse of the field in calculating total renewals over a date range.

Update loans_renewal_dates.sql for LDP

---

sql_metadb/derived_tables/loans_renewal_dates.sql

This PR closes issue#854
This is a revision of the loans_renewal_dates derived table in LDP. -- This uses the circulation_loan_history table for the data source; this table has been significantly changed since the derived table was originally created -- Changes to query: 
-- truncated the renewal date ("created date") to 'minutes' to eliminate renewals seconds apart, which are artifacts of system processes, not actual patron renewals.
-- added the item hrid
-- selected the loan status from the circulation_loans table, not the circulation_loan_history table (which always shows "Open" for renewals)
-- removed the loan history id ("id") from Select statement, since including it would make it impossible group by loan_id and count renewals
-- removed the "loan_renewal_count" field (selected …

Update loans_renewal_dates.sql derived table for Metadb
